const Images = {
  Pictures: {
    logo: require("../assets/images/logo.png"),
    logo_dark: require("../assets/images/logo-dark.png"),
    verified: require("../assets/images/verified.PNG"),
    profile: require("../assets/images/profile.png"),
    successCheck: require("../assets/images/check-circle.png"),
    userIcon: require("../assets/images/user-icon-img.png"),
    eclips: require("../assets/images/ellipse.svg"),
    brownLeftLeaf: require("../assets/images/brown-left-leaf.png"),
    brownRightLeaf: require("../assets/images/brown-right-leaf.png"),
    curvePathGradient: require("../assets/images/curve-Path.png"),
    emptyPlant: require("../assets/images/empty-plant.png"),
    chat: require("../assets/images/chat.png"),
    banner: [
      require("../assets/images/banner2.png"),
      require("../assets/images/banner3.png"),
      require("../assets/images/banner1.png"),
    ],
    payments: [
      require("../assets/images/pay1.png"),
      require("../assets/images/pay2.png"),
      require("../assets/images/pay3.png"),
      require("../assets/images/pay4.png"),
      require("../assets/images/pay5.png"),
      require("../assets/images/pay6.png"),
      require("../assets/images/pay7.png"),
      require("../assets/images/pay8.png"),
      require("../assets/images/pay9.png"),
    ],
    tabPayments: [
      require("../assets/images/tab-pay-1.png"),
      require("../assets/images/tab-pay-2.png"),
      require("../assets/images/tab-pay-3.png"),
      require("../assets/images/tab-pay-4.png"),
      require("../assets/images/tab-pay-5.png"),
      require("../assets/images/tab-pay-6.png"),
    ],
    slider: [require("../assets/images/slider1.png")],
    tradeImage: [require("../assets/images/trade-image.png")],
    plant: require("../assets/images/plant.png"),
    homeBanner: [
      require("../assets/images/background.png"),
      require("../assets/images/background2.png"),
    ],
    category: [
      require("../assets/images/category1.png"),
      require("../assets/images/category2.png"),
      require("../assets/images/category3.png"),
      require("../assets/images/category4.png"),
      require("../assets/images/category5.png"),
    ],
    agriculture: [
      require("../assets/images/card1.png"),
      require("../assets/images/card2.png"),
      require("../assets/images/card3.png"),
      require("../assets/images/card4.png"),
      require("../assets/images/card5.png"),
    ],
    agriculturalServices: [
      require("../assets/images/agricultural-service-1.png"),
      require("../assets/images/agricultural-service-2.png"),
      require("../assets/images/agricultural-service-3.png"),
      require("../assets/images/agricultural-service-4.png"),
      require("../assets/images/agricultural-service-5.png"),
      // require("../assets/images/agricultural-service-6.png"),
    ],
    allCategories: [
      require("../assets/images/category1.png"),
      require("../assets/images/category2.png"),
      require("../assets/images/category3.png"),
      require("../assets/images/category4.png"),
      require("../assets/images/category5.png"),
      // require("../assets/images/category.png"),
    ],
    topCategories: [
      require("../assets/images/category1.png"),
      require("../assets/images/category2.png"),
      require("../assets/images/category3.png"),
      require("../assets/images/category4.png"),
      require("../assets/images/category5.png"),
    ],
    service: [require("../assets/images/service-image1.png")],
    trade: [require("../assets/images/trade.png")],
    delevery: [
      require("../assets/images/delevery1.png"),
      require("../assets/images/delevery2.png"),
      require("../assets/images/delevery3.png"),
      require("../assets/images/delevery4.png"),
    ],
    clothing: require("../assets/images/clothing.png"),
    ads: require("../assets/images/ads.png"),
    product: [
      require("../assets/images/product.png"),
      require("../assets/images/product.png"),
      require("../assets/images/product.png"),
    ],
    flag: [require("../assets/images/flag.png")],
    greenRightDownLeaf: require("../assets/images/green-right-down-leaf.svg"),
    greenRightUpLeaf: require("../assets/images/green-right-up-leaf.png"),
  },
};

export default Images;
